contato e footer
jvwaldrich0/matrisys-portifolio-website pull request #11
Opened 2024-08-16 02:51 UTC by KneibL1

2024-08-16 16:12 UTC, jvwaldrich0 commented
![image](https://github.com/user-attachments/assets/cd28029c-41a1-4910-8ea7-c2dd2b1d7c62)

Criou problemas no CSS, mas temos alterações interessantes como o footer, script de rolagem de página e estrutura da área de contatos

2024-08-16 16:15 UTC, jvwaldrich0 requested changes

2024-08-16 16:15 UTC, jvwaldrich0 commented on assets/css/main.css
> +
Remover trecho de código, refatorar de outra forma

2024-08-16 16:15 UTC, jvwaldrich0 commented on assets/css/main.css
> +}
Aplicar clean code e parar de usar GPT para gerar código

2024-08-16 16:17 UTC, jvwaldrich0 commented on assets/css/main.css
> +}
@KneibL1

2024-08-16 16:17 UTC, jvwaldrich0 commented on assets/css/main.css
> +
@KneibL1

2024-08-17 19:46 UTC, KneibL1 commented on assets/css/main.css
> +}
NÃO

2024-08-20 17:15 UTC, closed without merging